### ISSUE TITLE
Fatal error: Cannot declare class upload

### ISSUE THREAD

**Issue by blueforce** [blueforce/png2k2#1]
Known issues in current Version 1.0.5

I get this error after saving an Item:
Fatal error: Cannot declare class upload, because the name is already in use in /ROOT/administrator/components/com_k2/lib/class.upload.php on line 624

this error appears only, if the plugin is active. the errormessage it's not related to K2 itself

and some other warnings like this:
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgK2Png4k2 has a deprecated constructor in /ROOT/plugins/k2/png4k2/png4k2.php on line 16

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; upload has a deprecated constructor in /ROOT/administrator/components/com_k2/lib/class.upload.php on line 624

**Comment by akhtar1985** [comment]
hi i got the error list below: how to resolve i required the k2 article images in png format. please help me  
joomla information below: 

Check | Result
-- | --

Web Server | Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.9
PHP version | 7.1.9
MySQL version | 5.5.5-10.1.26-MariaDB
GD image library | bundled (2.1.0 compatible)
Multibyte string support | Enabled
Upload limit | 2M
Memory limit | 128M
Open remote files (allow url fopen) | Yes
k2 png plugin error below: 
Notice: Only variables should be passed by reference in E:\xampp\htdocs\63746\plugins\k2\png4K2\png4k2.php on line 38

Warning: strtoupper() expects parameter 1 to be string, array given in E:\xampp\htdocs\63746\libraries\legacy\request\request.php on line 99

Warning: require_once(E:\xampp\htdocs\63746\administrator\components\com_k2\lib\class.upload.php): failed to open stream: No such file or directory in E:\xampp\htdocs\63746\plugins\k2\png4K2\png4k2.php on line 61

Fatal error: require_once(): Failed opening required 'E:\xampp\htdocs\63746\administrator\components\com_k2\lib\class.upload.php' (include_path='E:\xampp\php\PEAR') in E:\xampp\htdocs\63746\plugins\k2\png4K2\png4k2.php on line 61

**Comment by akhtar1985** [comment]
also i am test on joomla 3.8 and k2 2.8.0  php 5.6 version

error below:

Warning: strtoupper() expects parameter 1 to be string, array given in E:\xampp\htdocs\63746\libraries\legacy\request\request.php on line 99

Warning: require_once(E:\xampp\htdocs\63746\administrator\components\com_k2\lib\class.upload.php): failed to open stream: No such file or directory in E:\xampp\htdocs\63746\plugins\k2\png4K2\png4k2.php on line 61

Fatal error: require_once(): Failed opening required 'E:\xampp\htdocs\63746\administrator\components\com_k2\lib\class.upload.php' (include_path='E:\xampp\php\PEAR') in E:\xampp\htdocs\63746\plugins\k2\png4K2\png4k2.php on line 61

**Comment by Kubik-Rubik** [comment]
Fixed with https://github.com/blueforce/png2k2/pull/2

Cheers

**Comment by blueforce** [comment]
Thanks a lot! much appreciate!
